name: Drink Better Coffee
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74806
title: Drink Better Coffee
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#23232b'
    - '#ced8da'
    - '#f8f8f8'
    - '#9b9f9e'
    - '#8c7450'
  brandStrength: 0.6875
  lightness: 0.3125
  saturation: 0.6875
  rhythmicContrast: 0.8661702359095216
purpose: []
